name: Build and Push Docker Image



on:
    [workflow_dispatch]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Build Image

        run: |
          
          docker build -t manna888/arm-nvidia:latest .
          
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: manna888/arm-nvidia
          tags: |
            type=raw,value=latest
            type=raw,value=550
            type=raw,value=550_{{date 'YYYYMMDD'}}   

      - name: Publish Image

        run: |

          docker login -u manna888 -p ${{ secrets.DOCKERHUB_TOKEN }}
          
          docker push --all-tags manna888/arm-nvidia



          
